### ISSUE TITLE
Doesn't install on Python 3.5.2 + OS X 10.11.5

### ISSUE THREAD

**Issue by viniciusban** [thruflo/pyramid_simpleauth#10]
I'm running a virtualenv created exclusively for this test.

After installing Pyramid, I tried to install `pyramid_simpleauth`, but no success:

    (pyramid_simpleauth_example) example $ pip install pyramid_simpleauth
    Collecting pyramid_simpleauth
      Downloading pyramid_simpleauth-0.10.1.tar.gz
    Collecting pyramid_basemodel (from pyramid_simpleauth)
      Downloading pyramid_basemodel-0.3.6.tar.gz
    Collecting pyramid_simpleform (from pyramid_simpleauth)
      Downloading pyramid_simpleform-0.6.1.tar.gz
    Requirement already satisfied (use --upgrade to upgrade): pyramid in /Users/viniciusban/virtualenvs/pyramid_simpleauth_example/lib/python3.5/site-packages (from pyramid_simpleauth)
    Requirement already satisfied (use --upgrade to upgrade): pyramid_mako in /Users/viniciusban/virtualenvs/pyramid_simpleauth_example/lib/python3.5/site-packages (from pyramid_simpleauth)
    Requirement already satisfied (use --upgrade to upgrade): SQLAlchemy in /Users/viniciusban/virtualenvs/pyramid_simpleauth_example/lib/python3.5/site-packages (from pyramid_simpleauth)
    Collecting formencode (from pyramid_simpleauth)
      Downloading FormEncode-1.3.0.zip (347kB)
        100% |████████████████████████████████| 348kB 2.0MB/s 
    Collecting passlib (from pyramid_simpleauth)
      Downloading passlib-1.6.5-py2.py3-none-any.whl (317kB)
        100% |████████████████████████████████| 327kB 2.1MB/s 
    Collecting nose (from pyramid_simpleauth)
      Downloading nose-1.3.7-py3-none-any.whl (154kB)
        100% |████████████████████████████████| 163kB 2.6MB/s 
    Collecting mock (from pyramid_simpleauth)
      Downloading mock-2.0.0-py2.py3-none-any.whl (56kB)
        100% |████████████████████████████████| 61kB 3.1MB/s 
    Collecting paste (from pyramid_simpleauth)
      Downloading Paste-2.0.3-py34-none-any.whl (625kB)
        100% |████████████████████████████████| 634kB 1.5MB/s 
    Collecting webtest (from pyramid_simpleauth)
      Downloading WebTest-2.0.23-py2.py3-none-any.whl
    Collecting pyDNS (from pyramid_simpleauth)
      Downloading pydns-2.3.6.tar.gz
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/private/var/folders/tt/j992r5f94913rfnpsgqc52nc0000gn/T/pip-build-_e8myd8a/pyDNS/setup.py", line 12, in <module>
            import DNS
          File "/private/var/folders/tt/j992r5f94913rfnpsgqc52nc0000gn/T/pip-build-_e8myd8a/pyDNS/DNS/__init__.py", line 14, in <module>
            import Type,Opcode,Status,Class
        ImportError: No module named 'Type'
        
        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/tt/j992r5f94913rfnpsgqc52nc0000gn/T/pip-build-_e8myd8a/pyDNS/
    (pyramid_simpleauth_example) example $

It seems the problem is with `pyDNS`.

**Comment by thruflo** [comment]
See #8 and https://github.com/thruflo/pyramid_simpleauth/pull/9 -- definitely needs some Py3 love.
